// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable

namespace Jumia_Clone.Models.Entities;

public class Admin
{
    public int AdminId { get; set; }

    public int UserId { get; set; }

    public string Role { get; set; }

    public string Permissions { get; set; }

    public virtual User User { get; set; }
}