// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable


namespace Jumia_Clone.Models.Entities;

public class Affiliate
{
    public int AffiliateId { get; set; }

    public int UserId { get; set; }

    public string AffiliateCode { get; set; }

    public decimal? CommissionRate { get; set; }

    public decimal? TotalEarnings { get; set; }

    public decimal? AvailableBalance { get; set; }

    public decimal? WithdrawnAmount { get; set; }

    public DateTime? CreatedAt { get; set; }

    public bool? IsActive { get; set; }

    public virtual ICollection<AffiliateCommission> AffiliateCommissions { get; set; } = new List<AffiliateCommission>();

    public virtual ICollection<AffiliateSellerRelationship> AffiliateSellerRelationships { get; set; } = new List<AffiliateSellerRelationship>();

    public virtual ICollection<AffiliateWithdrawal> AffiliateWithdrawals { get; set; } = new List<AffiliateWithdrawal>();

    public virtual ICollection<Order> Orders { get; set; } = new List<Order>();

    public virtual User User { get; set; }
}