// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable

namespace Jumia_Clone.Models.Entities;

public class AffiliateWithdrawal
{
    public int WithdrawalId { get; set; }

    public int AffiliateId { get; set; }

    public decimal Amount { get; set; }

    public string PaymentMethod { get; set; }

    public string PaymentDetails { get; set; }

    public string Status { get; set; }

    public DateTime? RequestedAt { get; set; }

    public DateTime? ProcessedAt { get; set; }

    public string Notes { get; set; }

    public virtual Affiliate Affiliate { get; set; }
}