// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable

namespace Jumia_Clone.Models.Entities;

public class AffiliateCommission
{
    public int CommissionId { get; set; }

    public int AffiliateId { get; set; }

    public int OrderId { get; set; }

    public int SuborderId { get; set; }

    public int SellerId { get; set; }

    public int OrderItemId { get; set; }

    public int ProductId { get; set; }

    public decimal CommissionAmount { get; set; }

    public decimal CommissionRate { get; set; }

    public decimal OrderItemTotal { get; set; }

    public string Status { get; set; }

    public DateTime? CreatedAt { get; set; }

    public DateTime? UpdatedAt { get; set; }

    public DateTime? PaidAt { get; set; }

    public virtual Affiliate Affiliate { get; set; }

    public virtual Order Order { get; set; }

    public virtual OrderItem OrderItem { get; set; }

    public virtual Product Product { get; set; }

    public virtual Seller Seller { get; set; }

    public virtual SubOrder Suborder { get; set; }
}