// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable

namespace Jumia_Clone.Models.Entities;

public class CartItem
{
    public int CartItemId { get; set; }

    public int CartId { get; set; }

    public int ProductId { get; set; }

    public int Quantity { get; set; }

    public decimal PriceAtAddition { get; set; }

    public int? VariantId { get; set; }

    public virtual Cart Cart { get; set; }

    public virtual Product Product { get; set; }

    public virtual ProductVariant Variant { get; set; }
}

