// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable

namespace Jumia_Clone.Models.Entities;

public class Coupon
{
    public int CouponId { get; set; }

    public string Code { get; set; }

    public string Description { get; set; }

    public decimal DiscountAmount { get; set; }

    public decimal? MinimumPurchase { get; set; }

    public string DiscountType { get; set; }

    public DateTime StartDate { get; set; }

    public DateTime EndDate { get; set; }

    public bool? IsActive { get; set; }

    public int? UsageLimit { get; set; }

    public int? UsageCount { get; set; }

    public virtual ICollection<Order> Orders { get; set; } = new List<Order>();

    public virtual ICollection<UserCoupon> UserCoupons { get; set; } = new List<UserCoupon>();
}