// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>

namespace Jumia_Clone.Models.Entities
{
    public class create_orderResult
    {
        public int? order_id { get; set; }
    }
}
