// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable

namespace Jumia_Clone.Models.Entities;

public class HelpfulRating
{
    public int HelpfulId { get; set; }

    public int RatingId { get; set; }

    public int CustomerId { get; set; }

    public bool IsHelpful { get; set; }

    public virtual Customer Customer { get; set; }

    public virtual Rating Rating { get; set; }
}