// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable


namespace Jumia_Clone.Models.Entities;

public class Order
{
    public int OrderId { get; set; }

    public int CustomerId { get; set; }

    public int AddressId { get; set; }

    public int? CouponId { get; set; }

    public decimal TotalAmount { get; set; }

    public decimal? DiscountAmount { get; set; }

    public decimal? ShippingFee { get; set; }

    public decimal? TaxAmount { get; set; }

    public decimal FinalAmount { get; set; }

    public string PaymentMethod { get; set; }

    public string PaymentStatus { get; set; }

    public DateTime? CreatedAt { get; set; }
    public string OrderStatus { get; set; }
    public DateTime? UpdatedAt { get; set; }

    public int? AffiliateId { get; set; }

    public string AffiliateCode { get; set; }

    public virtual Address Address { get; set; }

    public virtual Affiliate Affiliate { get; set; }

    public virtual ICollection<AffiliateCommission> AffiliateCommissions { get; set; } = new List<AffiliateCommission>();

    public virtual Coupon Coupon { get; set; }

    public virtual Customer Customer { get; set; }

    public virtual ICollection<SubOrder> SubOrders { get; set; } = new List<SubOrder>();
}