// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable


namespace Jumia_Clone.Models.Entities;

public class ProductVariant
{
    public int VariantId { get; set; }

    public int ProductId { get; set; }

    public string VariantName { get; set; }

    public decimal Price { get; set; }

    public decimal? DiscountPercentage { get; set; }

    public int StockQuantity { get; set; }

    public string Sku { get; set; }

    public string VariantImageUrl { get; set; }

    public bool? IsDefault { get; set; }

    public bool? IsAvailable { get; set; }

    public virtual ICollection<CartItem> CartItems { get; set; } = new List<CartItem>();

    public virtual ICollection<OrderItem> OrderItems { get; set; } = new List<OrderItem>();

    public virtual Product Product { get; set; }

    public virtual ICollection<VariantAttribute> VariantAttributes { get; set; } = new List<VariantAttribute>();
}