// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable

namespace Jumia_Clone.Models.Entities;

public class ProductAttribute
{
    public int AttributeId { get; set; }

    public int SubcategoryId { get; set; }

    public string Name { get; set; }

    public string Type { get; set; }

    public string PossibleValues { get; set; }

    public bool? IsRequired { get; set; }

    public bool? IsFilterable { get; set; }

    public virtual ICollection<ProductAttributeValue> ProductAttributeValues { get; set; } = new List<ProductAttributeValue>();

    public virtual SubCategory Subcategory { get; set; }
}