// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable

namespace Jumia_Clone.Models.Entities;

public class ProductView
{
    public int ViewId { get; set; }

    public int ProductId { get; set; }

    public int? CustomerId { get; set; }

    public string SessionId { get; set; }

    public DateTime? ViewedAt { get; set; }

    public virtual Customer Customer { get; set; }

    public virtual Product Product { get; set; }
}