// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable


namespace Jumia_Clone.Models.Entities;

public class Product
{
    public int ProductId { get; set; }

    public int SellerId { get; set; }

    public int SubcategoryId { get; set; }

    public string Name { get; set; }

    public string Description { get; set; }

    public decimal BasePrice { get; set; }

    public decimal? DiscountPercentage { get; set; }

    public bool? IsAvailable { get; set; }

    public string ApprovalStatus { get; set; }

    public DateTime? CreatedAt { get; set; }

    public DateTime? UpdatedAt { get; set; }

    public int StockQuantity { get; set; }

    public string MainImageUrl { get; set; }

    public double? AverageRating { get; set; }

    public virtual ICollection<AffiliateCommission> AffiliateCommissions { get; set; } = new List<AffiliateCommission>();

    public virtual ICollection<CartItem> CartItems { get; set; } = new List<CartItem>();

    public virtual ICollection<OrderItem> OrderItems { get; set; } = new List<OrderItem>();

    public virtual ICollection<ProductAttributeValue> ProductAttributeValues { get; set; } = new List<ProductAttributeValue>();

    public virtual ICollection<ProductImage> ProductImages { get; set; } = new List<ProductImage>();

    public virtual ICollection<ProductRecommendation> ProductRecommendationRecommendedProducts { get; set; } = new List<ProductRecommendation>();

    public virtual ICollection<ProductRecommendation> ProductRecommendationSourceProducts { get; set; } = new List<ProductRecommendation>();

    public virtual ICollection<ProductVariant> ProductVariants { get; set; } = new List<ProductVariant>();

    public virtual ICollection<ProductView> ProductViews { get; set; } = new List<ProductView>();

    public virtual ICollection<Rating> Ratings { get; set; } = new List<Rating>();

    public virtual ICollection<SearchResultClick> SearchResultClicks { get; set; } = new List<SearchResultClick>();

    public virtual Seller Seller { get; set; }

    public virtual SubCategory Subcategory { get; set; }

    public virtual ICollection<TrendingProduct> TrendingProducts { get; set; } = new List<TrendingProduct>();

    public virtual ICollection<UserProductInteraction> UserProductInteractions { get; set; } = new List<UserProductInteraction>();

    public virtual ICollection<UserRecommendation> UserRecommendations { get; set; } = new List<UserRecommendation>();

    public virtual ICollection<WishlistItem> WishlistItems { get; set; } = new List<WishlistItem>();
}