// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable

namespace Jumia_Clone.Models.Entities;

public class Rating
{
    public int RatingId { get; set; }

    public int CustomerId { get; set; }

    public int ProductId { get; set; }

    public int Stars { get; set; }

    public string Comment { get; set; }

    public DateTime? CreatedAt { get; set; }

    public bool? IsVerifiedPurchase { get; set; }

    public int? HelpfulCount { get; set; }

    public virtual Customer Customer { get; set; }

    public virtual ICollection<HelpfulRating> HelpfulRatings { get; set; } = new List<HelpfulRating>();

    public virtual Product Product { get; set; }

    public virtual ICollection<ReviewImage> ReviewImages { get; set; } = new List<ReviewImage>();
}