// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable


namespace Jumia_Clone.Models.Entities;

public class ReturnItem
{
    public int ReturnItemId { get; set; }

    public int ReturnId { get; set; }

    public int OrderItemId { get; set; }

    public int Quantity { get; set; }

    public string ReturnReason { get; set; }

    public string Condition { get; set; }

    public decimal? RefundAmount { get; set; }

    public virtual OrderItem OrderItem { get; set; }

    public virtual ReturnRequest Return { get; set; }
}