// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable

namespace Jumia_Clone.Models.Entities;

public class ReturnRequest
{
    public int ReturnId { get; set; }

    public int SuborderId { get; set; }

    public int CustomerId { get; set; }

    public string ReturnReason { get; set; }

    public string ReturnStatus { get; set; }

    public DateTime? RequestedAt { get; set; }

    public DateTime? ApprovedAt { get; set; }

    public DateTime? ReceivedAt { get; set; }

    public decimal? RefundAmount { get; set; }

    public DateTime? RefundedAt { get; set; }

    public string TrackingNumber { get; set; }

    public string Comments { get; set; }

    public virtual Customer Customer { get; set; }

    public virtual ICollection<ReturnItem> ReturnItems { get; set; } = new List<ReturnItem>();

    public virtual SubOrder Suborder { get; set; }
}