// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable

namespace Jumia_Clone.Models.Entities;

public class ReviewImage
{
    public int ReviewImageId { get; set; }

    public int RatingId { get; set; }

    public string ImageUrl { get; set; }

    public virtual Rating Rating { get; set; }
}