// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable

namespace Jumia_Clone.Models.Entities;

public class SearchHistory
{
    public int SearchId { get; set; }

    public int? CustomerId { get; set; }

    public string SessionId { get; set; }

    public string SearchQuery { get; set; }

    public DateTime? SearchTime { get; set; }

    public int? ResultCount { get; set; }

    public int? CategoryId { get; set; }

    public int? SubcategoryId { get; set; }

    public string Filters { get; set; }

    public virtual Category Category { get; set; }

    public virtual Customer Customer { get; set; }

    public virtual ICollection<SearchResultClick> SearchResultClicks { get; set; } = new List<SearchResultClick>();

    public virtual SubCategory Subcategory { get; set; }
}