// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable

namespace Jumia_Clone.Models.Entities;

public class SearchResultClick
{
    public int ClickId { get; set; }

    public int SearchId { get; set; }

    public int ProductId { get; set; }

    public DateTime? ClickTime { get; set; }

    public int? PositionInResults { get; set; }

    public virtual Product Product { get; set; }

    public virtual SearchHistory Search { get; set; }
}