// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable

namespace Jumia_Clone.Models.Entities;

public class Seller
{
    public int SellerId { get; set; }

    public int UserId { get; set; }

    public string BusinessName { get; set; }

    public string BusinessDescription { get; set; }

    public string BusinessLogo { get; set; }

    public bool? IsVerified { get; set; }

    public DateTime? VerifiedAt { get; set; }

    public double? Rating { get; set; }

    public virtual ICollection<AffiliateCommission> AffiliateCommissions { get; set; } = new List<AffiliateCommission>();

    public virtual ICollection<AffiliateSellerRelationship> AffiliateSellerRelationships { get; set; } = new List<AffiliateSellerRelationship>();

    public virtual ICollection<Product> Products { get; set; } = new List<Product>();

    public virtual ICollection<SubOrder> SubOrders { get; set; } = new List<SubOrder>();

    public virtual User User { get; set; }
}