// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable

using System.Text.Json.Serialization;

namespace Jumia_Clone.Models.Entities;

public class SubOrder
{
    public int SuborderId { get; set; }

    public int OrderId { get; set; }

    public int SellerId { get; set; }

    public decimal Subtotal { get; set; }

    public string Status { get; set; }

    public DateTime? StatusUpdatedAt { get; set; }

    public string TrackingNumber { get; set; }

    public string ShippingProvider { get; set; }

    public virtual ICollection<AffiliateCommission> AffiliateCommissions { get; set; } = new List<AffiliateCommission>();

    [JsonIgnore]
    public virtual Order Order { get; set; }

    public virtual ICollection<OrderItem> OrderItems { get; set; } = new List<OrderItem>();

    public virtual ICollection<ReturnRequest> ReturnRequests { get; set; } = new List<ReturnRequest>();

    public virtual Seller Seller { get; set; }
}