// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable

namespace Jumia_Clone.Models.Entities;

public class TrendingProduct
{
    public int TrendingId { get; set; }

    public int ProductId { get; set; }

    public int? CategoryId { get; set; }

    public int? SubcategoryId { get; set; }

    public decimal TrendScore { get; set; }

    public string TimePeriod { get; set; }

    public DateTime? LastUpdated { get; set; }

    public virtual Category Category { get; set; }

    public virtual Product Product { get; set; }

    public virtual SubCategory Subcategory { get; set; }
}