// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable

namespace Jumia_Clone.Models.Entities;

public class UserCoupon
{
    public int UserCouponId { get; set; }

    public int CustomerId { get; set; }

    public int CouponId { get; set; }

    public bool? IsUsed { get; set; }

    public DateTime? AssignedAt { get; set; }

    public DateTime? UsedAt { get; set; }

    public virtual Coupon Coupon { get; set; }

    public virtual Customer Customer { get; set; }
}