// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable


namespace Jumia_Clone.Models.Entities;

public class UserProductInteraction
{
    public int InteractionId { get; set; }

    public int? CustomerId { get; set; }

    public string SessionId { get; set; }

    public int ProductId { get; set; }

    public string InteractionType { get; set; }

    public DateTime? InteractionTime { get; set; }

    public int? DurationSeconds { get; set; }

    public string InteractionData { get; set; }

    public virtual Customer Customer { get; set; }

    public virtual Product Product { get; set; }
}