// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable


using System.ComponentModel.DataAnnotations;

namespace Jumia_Clone.Models.Entities;

public class User
{
    public int UserId { get; set; }

    public string Email { get; set; }

    public string PasswordHash { get; set; }

    public string FirstName { get; set; }

    public string LastName { get; set; }

    public string PhoneNumber { get; set; }

    public DateTime? CreatedAt { get; set; }

    public DateTime? UpdatedAt { get; set; }

    public string UserType { get; set; }

    public bool? IsActive { get; set; }
    [MaxLength(250)]
    public string ProfileImageUrl { get; set; }
    public virtual ICollection<Address> Addresses { get; set; } = new List<Address>();

    public virtual Admin Admin { get; set; }

    public virtual ICollection<Affiliate> Affiliates { get; set; } = new List<Affiliate>();

    public virtual Customer Customer { get; set; }

    public virtual Seller Seller { get; set; }
}