// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable

namespace Jumia_Clone.Models.Entities;

public class UserRecommendation
{
    public int UserRecommendationId { get; set; }

    public int CustomerId { get; set; }

    public int ProductId { get; set; }

    public string RecommendationType { get; set; }

    public decimal Score { get; set; }

    public DateTime? LastUpdated { get; set; }

    public virtual Customer Customer { get; set; }

    public virtual Product Product { get; set; }
}