// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable

namespace Jumia_Clone.Models.Entities;

public class VariantAttribute
{
    public int VariantAttributeId { get; set; }

    public int VariantId { get; set; }

    public string AttributeName { get; set; }

    public string AttributeValue { get; set; }

    public virtual ProductVariant Variant { get; set; }
}